logging:
  level.org.springframework: INFO
  level.com.at: DEBUG
spring:
  datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    password:
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: david01
  jpa:
    show-sql: false
    format-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect